# Generated by Django 3.2.6 on 2021-09-27 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppResult', '0003_teachermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentResultModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=50)),
                ('student_first_name', models.CharField(max_length=50)),
                ('student_last_name', models.CharField(max_length=50)),
                ('admission_std', models.CharField(max_length=50)),
                ('admission_stream', models.CharField(max_length=50)),
                ('teacher_id', models.CharField(max_length=50)),
                ('subject_name', models.CharField(max_length=50)),
                ('english', models.IntegerField()),
                ('maths', models.IntegerField()),
                ('science', models.IntegerField()),
                ('computer', models.IntegerField()),
                ('total_marks', models.IntegerField()),
                ('result', models.CharField(choices=[(None, 'Select Result'), ('Fail', 'Fail'), ('Pass', 'Pass')], default=None, max_length=50)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
