# Generated by Django 3.2.6 on 2021-09-28 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppResult', '0005_auto_20210928_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentresultmodel',
            name='result',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='studentresultmodel',
            name='student_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name_s', to='AppResult.studentregistrationmodel'),
        ),
    ]
