# Generated by Django 3.2.6 on 2021-09-28 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppResult', '0006_auto_20210928_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresultmodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterUniqueTogether(
            name='studentresultmodel',
            unique_together={('maths', 'computer')},
        ),
    ]
