# Generated by Django 3.2.6 on 2021-09-29 06:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppResult', '0009_auto_20210929_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentresultmodel',
            name='english',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='studentresultmodel',
            name='student_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name_s', to='AppResult.studentregistrationmodel', unique=True),
        ),
    ]
