# Generated by Django 3.2.6 on 2021-09-29 08:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppResult', '0010_auto_20210929_1207'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeacherModel',
        ),
        migrations.AlterField(
            model_name='studentresultmodel',
            name='computer',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='studentresultmodel',
            name='maths',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='studentresultmodel',
            name='science',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='studentresultmodel',
            name='student_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Result', to='AppResult.studentregistrationmodel', unique=True),
        ),
    ]
