# Generated by Django 3.2.6 on 2021-09-29 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppResult', '0011_auto_20210929_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentregistrationmodel',
            name='leave_date',
        ),
        migrations.AlterField(
            model_name='studentregistrationmodel',
            name='admission_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
