# Generated by Django 3.2.6 on 2021-09-29 11:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppResult', '0012_auto_20210929_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentregistrationmodel',
            name='admission_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='studentregistrationmodel',
            name='percentage',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='studentregistrationmodel',
            name='student_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
